### ISSUE TITLE
Can't decode Hue Lights API Version 1.0

### ISSUE THREAD

**Issue by damienklinnert** [damienklinnert/elm-hue#5]
With PR #1 @torresmi demonstrated that this module fails to decode responses from the lights API Version 1.0. That is because the decoder is expecting two fields which are not part of v1.0, namely:
- `manufacturername` existing since v1.7
- `unique` existing since v1.4

The question is how do we best go forward from here? I see two possible approaches:
## 1. Default to empty strings

Since both fields are strings, we could set their value to empty strings, if they don't exist. The advantage of it is that we wouldn't break the api and wouldn't need a major bump. The downside is that we'd loose type safety.
## 2. Change data structures to use Maybe's

We could expose the fields that we're added later as `Maybe String` - setting them to `Nothing` if we're on an older API version. This would require a major version bump, but bring in type safety.

@torresmi which approach do you prefer?

**Comment by torresmi** [comment]
:+1: for option 2

After using the Hue API with a less safe language ( Java 6 :unamused: ), I'm leaning more towards relying on Elm's type system for this. The API complexity would increase a bit, but having type guarantees and tests to make a rock-solid safe Hue API would be awesome.

I could see a case where a consumer would see that `uniqueid` is not a `Maybe`, and thus make the assumption that a _unique_ id will always be there. It then compiles and everything seems fine, except strange things are happening on old versions because the ids are the same.
